apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-gallery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-gallery
  template:
    metadata:
      labels:
        app: bird-gallery
    spec:
      nodename: 10.0.88.201
      initContainers:
      - name: scraper
        image: bird-gallery:latest
        command: ['python', 'bird_scraper.py']
        env:
        - name: FLASK_VERSION
          value: "2.0.1"
        - name: WERKZEUG_VERSION
          value: "2.0.1"
        volumeMounts:
        - name: shared-data
          mountPath: /app/static
      containers:
      - name: web
        image: bird-gallery:latest
        env:
        - name: FLASK_VERSION
          value: "2.0.1"
        - name: WERKZEUG_VERSION
          value: "2.0.1"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-data
          mountPath: /app/static
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: shared-data
        emptyDir: {} 